### ISSUE TITLE
Eigen resizing errors

### ISSUE THREAD

**Issue by vnigolian** [duxingyi-charles/Total-Lifted-Content-PN#1]
Hi, I'm currently trying to run the code on a bunch of tet meshes and I get an "invalid sizes" error from eigen for all of them.
Note that I ran the QN version on my dataset without any issues.

**Comment by duxingyi-charles** [comment]
The code only includes PN for triangle meshes, not tet meshes. That's why the input size is invalid.
I plan to release the PN solver for tet mesh with my new paper in Siggraph Asia (https://duxingyi-charles.github.io/publication/isometric-energies-for-recovering-injectivity-in-constrained-mapping/).
